CREATE TABLE IF NOT EXISTS sys_ai_quality_gate_run (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  run_id VARCHAR(64) NOT NULL,
  resource_type VARCHAR(32) NOT NULL,
  resource_id BIGINT UNSIGNED NOT NULL,
  resource_name VARCHAR(128) NOT NULL,
  resource_version VARCHAR(64) NOT NULL,
  status VARCHAR(16) NOT NULL,
  total INT NOT NULL DEFAULT 0,
  completed INT NOT NULL DEFAULT 0,
  current_sample VARCHAR(64) NULL,
  samples TEXT NULL,
  summary TEXT NULL,
  metrics TEXT NULL,
  error TEXT NULL,
  started_at DATETIME(3) NULL,
  finished_at DATETIME(3) NULL,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_sys_ai_quality_gate_run_run_id (run_id),
  KEY idx_sys_ai_quality_gate_run_resource (resource_type, resource_id),
  KEY idx_sys_ai_quality_gate_run_status (status),
  KEY idx_sys_ai_quality_gate_run_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
